# Site settings
title: Mozilla Campus Clubs
email: participation@mozilla.com
description: >
    Get involved with the Campus initiatives at Mozilla
baseurl: ""
url: "https://campus.mozilla.community"
twitter_username: mozparticipate
github_username:  mozilla

# Build settings
markdown: kramdown

include: ['_pages']
